# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='remotedevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('ipeth0', models.CharField(max_length=16)),
                ('ipeth1', models.CharField(max_length=16)),
            ],
        ),
    ]
